#!/bin/bash

echo "Wait..."
lfu_answers=()
for i in {1..10};
    do 
    lfu_answers+=("$(../Cache/build/cache < ${i}test.txt)");
    done
ideal_answers=()
for i in {1..10};
    do 
    ideal_answers+=("$(../Cache/build/ideal_cache < ${i}test.txt)");
    done
for ((i=0; i < ${#lfu_answers[@]}; i++ ));
    do
    echo "LFU: ${lfu_answers[$i]}, Ideal: ${ideal_answers[$i]}";
    done
